apply plugin: 'com.android.application'

android {
  namespace 'com.example.duktape.octane'
  buildToolsVersion = rootProject.ext.buildToolsVersion
  compileSdk rootProject.ext.compileSdk

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

  defaultConfig {
    applicationId 'com.example.duktape.octane'
    minSdk rootProject.ext.minSdk
    targetSdk rootProject.ext.targetSdk
  }

  signingConfigs {
    samples {
      storeFile file('samples.keystore')
      storePassword 'javascript'
      keyAlias 'javascript'
      keyPassword 'javascript'
    }
  }

  buildTypes {
    debug {
      applicationIdSuffix '.debug'
      signingConfig signingConfigs.samples
    }
    release {
      signingConfig signingConfigs.samples
    }
  }
}

dependencies {
  implementation project(':quickjs:android')
  implementation deps.duktape
  implementation deps.okio
}
